.TH "includes Directory Reference" 3 "Sat Apr 15 2017" "Version V1.0" "Gestion de AWS con Sockets - TP1 SOII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclient_info\&.h\fP"
.br
.RI "\fIDatos y estructuras relacionados al Cliente\&. \fP"
.ti -1c
.RI "file \fBestaciones\&.h\fP"
.br
.RI "\fIEstructuras relacionadas a las ESTACIONES_H\&. \fP"
.ti -1c
.RI "file \fBparse_functions\&.h\fP"
.br
.RI "\fIFunciones para el parseo de datos\&. \fP"
.ti -1c
.RI "file \fBserver_functions\&.h\fP"
.br
.RI "\fIFunciones del servidor\&. \fP"
.ti -1c
.RI "file \fBsocket_functions\&.h\fP"
.br
.RI "\fIFunciones para el uso de sockets\&. \fP"
.in -1c
