.TH "includes/client_info.h" 3 "Sat Apr 15 2017" "Version V1.0" "Gestion de AWS con Sockets - TP1 SOII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/client_info.h \- Datos y estructuras relacionados al Cliente\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKNRM\fP   '\\x1B[0m'"
.br
.RI "\fIDefine color del Prompt\&. \fP"
.ti -1c
.RI "#define \fBKBLD\fP   '\\033[1m'"
.br
.RI "\fIDefine color del Prompt\&. \fP"
.ti -1c
.RI "#define \fBKYEL\fP   '\\x1B[33m'"
.br
.RI "\fIDefine color del Prompt\&. \fP"
.ti -1c
.RI "#define \fBKMAG\fP   '\\x1B[35m'"
.br
.RI "\fIDefine color del Prompt\&. \fP"
.ti -1c
.RI "#define \fBKCYN\fP   '\\x1B[36m'"
.br
.RI "\fIDefine color del Prompt\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBclient_prompt\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Datos y estructuras relacionados al Cliente\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestion de AWS con Sockets - TP1 SOII from the source code\&.
