.TH "Client_info" 3 "Sat Apr 15 2017" "Version V1.0" "Gestion de AWS con Sockets - TP1 SOII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client_info \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBusuario\fP"
.br
.ti -1c
.RI "char * \fBip_conexion\fP"
.br
.ti -1c
.RI "char * \fBpuerto\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Gestion de AWS con Sockets - TP1 SOII from the source code\&.
