.TH "includes/estaciones.h" 3 "Sun Apr 16 2017" "Version V1.0" "Gestion de AWS con Sockets - TP1 SOII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/estaciones.h \- Estructuras relacionadas a las ESTACIONES_H\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <time\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEstacion\fP"
.br
.RI "\fIGuarda los valores de las estaciones\&. \fP"
.ti -1c
.RI "struct \fBVariables\fP"
.br
.RI "\fIGuarda los valores de la variables de una estacion\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_XOPEN_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP"
.br
.ti -1c
.RI "#define \fBNUM_ESTACIONES\fP   5"
.br
.RI "\fICantidad de estaciones\&. \fP"
.ti -1c
.RI "#define \fBMAX_ESTACIONES\fP   18303"
.br
.RI "\fICantidad de datos de estaciones en el documento\&. \fP"
.ti -1c
.RI "#define \fBNUM_CAMPOS\fP   19"
.br
.RI "\fICantidad de \fBVariables\fP de las estaciones\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Estructuras relacionadas a las ESTACIONES_H\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestion de AWS con Sockets - TP1 SOII from the source code\&.
