.TH "Variables" 3 "Sun Apr 16 2017" "Version V1.0" "Gestion de AWS con Sockets - TP1 SOII" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Variables \- Guarda los valores de la variables de una estacion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <estaciones\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBtemperatura\fP"
.br
.ti -1c
.RI "float \fBhumedad\fP"
.br
.ti -1c
.RI "float \fBpunto_rocio\fP"
.br
.ti -1c
.RI "float \fBprecipitacion\fP"
.br
.ti -1c
.RI "float \fBvelocidad_viento\fP"
.br
.ti -1c
.RI "float \fBrafaga_max\fP"
.br
.ti -1c
.RI "float \fBpresion\fP"
.br
.ti -1c
.RI "float \fBradiacion_solar\fP"
.br
.ti -1c
.RI "float \fBtemperatura_suelo1\fP"
.br
.ti -1c
.RI "float \fBtemperatura_suelo2\fP"
.br
.ti -1c
.RI "float \fBtemperatura_suelo3\fP"
.br
.ti -1c
.RI "float \fBhumedad_suelo1\fP"
.br
.ti -1c
.RI "float \fBhumedad_suelo2\fP"
.br
.ti -1c
.RI "float \fBhumedad_suelo3\fP"
.br
.ti -1c
.RI "float \fBhumedad_hoja\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Guarda los valores de la variables de una estacion\&. 


.PP
\fBParameters:\fP
.RS 4
\fItemperatura\fP 
.br
\fIhumedad\fP 
.br
\fIpunto_rocio\fP 
.br
\fItemperatura\fP 
.br
\fIhumedad\fP 
.br
\fIpunto_rocio\fP 
.br
\fIprecipitacion\fP 
.br
\fIvelocidad_viento\fP 
.br
\fIrafaga_max\fP 
.br
\fIpresion\fP 
.br
\fIradiacion_solar\fP 
.br
\fItemperatura_suelo1\fP 
.br
\fItemperatura_suelo2\fP 
.br
\fItemperatura_suelo3\fP 
.br
\fIhumedad_suelo1\fP 
.br
\fIhumedad_suelo2\fP 
.br
\fIhumedad_suelo3\fP float humedad_hoja 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Gestion de AWS con Sockets - TP1 SOII from the source code\&.
